# ##Applications of R Matrices

In geology, matrices are used for taking surveys and also used for plotting graphs, statistics, and studies in different fields.

To represent the real world data is like traits of people’s population. They are the best representation method for plotting common survey things.

In robotics and automation, matrices are the best elements for the robot movements.

Matrices are used in calculating the gross domestic products in Economics. Therefore, it helps in calculating the efficiency of goods and products.

In computer-based application, matrices play a vital role in the projection of three-dimensional image into a two-dimensional screen, creating a realistic seeming motion.

In physical related applications, matrices can be applied in the study of an electrical circuit.

In [ ]:
matrix(data, nrow, ncol, byrow, dimnames)

Where,

Data is the input vector. This can also include a list or an expression.
Nrow is the number of rows that we wish to create in our matrix.
Ncol is the specification of the number of columns in our matrix.
Byrow is a logical attribute which is FALSE by default. Setting it true will arrange the input vectors by row.
Dimnames allows you to name rows and columns in a matrix.

In [6]:
mat <- matrix (
c(2 , 4, 3, 1, 5, 7),       # the data elements
nrow =2,                   # no. of rows
ncol =3,                   # no. of columns
byrow = FALSE)                # Default: FALSE
mat

[,1] [,2] [,3]
[1,] 2    3    5   
[2,] 4    1    7

In [7]:
mat[2, 3]
mat[2, ]
mat[ ,3]

[1] 7

[1] 4 1 7

[1] 5 7

In [8]:
arrang_row <- matrix(c(4:15), nrow = 4, byrow = TRUE) #Creating our matrix and arranging it by row
print(arrang_row) #Printing our arranged matrix

     [,1] [,2] [,3]
[1,]    4    5    6
[2,]    7    8    9
[3,]   10   11   12
[4,]   13   14   15


In [13]:
arrang_col <- matrix(c(4:15), nrow = 4, byrow = FALSE)     
#Creating our matrix and arranging it by column
print(arrang_col)

     [,1] [,2] [,3]
[1,]    4    8   12
[2,]    5    9   13
[3,]    6   10   14
[4,]    7   11   15


In [14]:
rows = c("row1", "row2", "row3", "row4")     #Creating our character vector of row names

cols = c("colm1", "colm2", "colm3")          #Creating our character vector of column names

mat <- matrix(c(4:15), nrow = 4, byrow = TRUE, dimnames = list(rows, cols) )   
#creating our matrix mat and assigning our vectors to dimnames

print(mat)                    #Printing our matrix

     colm1 colm2 colm3
row1     4     5     6
row2     7     8     9
row3    10    11    12
row4    13    14    15


In [44]:
print(mat['row1','colm3'])

[1] 0


In [17]:
 print(mat[2, ])

colm1 colm2 colm3 
    7     8     9 


In [18]:
print(mat[ , 2])

row1 row2 row3 row4 
   5    8   11   14 


In [19]:
mat    #Displaying values of matrix mat

mat[2,3] <- 20  #Assigning value 20 to the element at 2nd row and 3rd column
mat   		#Displaying our modified matrix.

colm1 colm2 colm3
row1  4     5     6   
row2  7     8     9   
row3 10    11    12   
row4 13    14    15

colm1 colm2 colm3
row1  4     5     6   
row2  7     8    20   
row3 10    11    12   
row4 13    14    15

In [20]:
mat[mat == 4] <- 0     #Replacing elements that are equal to 4 with 0
mat  			#Displaying our modified matrix ‘mat’

colm1 colm2 colm3
row1  0     5     6   
row2  7     8    20   
row3 10    11    12   
row4 13    14    15

In [21]:
mat[mat < 10] <- 0       #Replacing elements that are less with 10 with 0
mat

colm1 colm2 colm3
row1  0     0     0   
row2  0     0    20   
row3 10    11    12   
row4 13    14    15

In [49]:
new_mat = matrix(1:12, nrow = 3, ncol = 3)
new_mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [51]:
a=cbind(new_mat, c(1,2,3))
print(new_mat)
print(a)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
     [,1] [,2] [,3] [,4]
[1,]    1    4    7    1
[2,]    2    5    8    2
[3,]    3    6    9    3


In [40]:
rbind(new_mat, c(1,2,3))

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   
[4,] 1    2    3

In [53]:
dim(new_mat) <- c(9,1)
print(new_mat)

      [,1]
 [1,]    1
 [2,]    2
 [3,]    3
 [4,]    4
 [5,]    5
 [6,]    6
 [7,]    7
 [8,]    8
 [9,]    9


In [54]:
dim(new_mat) <- c(3,3)
new_mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [28]:
t(new_mat)   #transpose

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [31]:
mat1 <- matrix(data = 1:8, nrow = 4, ncol = 4) #Creating our first matrix mat1
mat1
mat2 <- matrix(data = 1:16, nrow = 4, ncol = 4) #Creating our second matrix mat2
mat2

[,1] [,2] [,3] [,4]
[1,] 1    5    1    5   
[2,] 2    6    2    6   
[3,] 3    7    3    7   
[4,] 4    8    4    8

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [30]:
sum <- mat1 + mat2 #Adding our two matrices
print(sum) #Printing the sum

     [,1] [,2] [,3] [,4]
[1,]    2   10   10   18
[2,]    4   12   12   20
[3,]    6   14   14   22
[4,]    8   16   16   24


In [32]:
sub <- mat1 - mat2 #Adding our two matrices
print(sub) #Printing the sum

     [,1] [,2] [,3] [,4]
[1,]    0    0   -8   -8
[2,]    0    0   -8   -8
[3,]    0    0   -8   -8
[4,]    0    0   -8   -8


In [57]:
prod <- mat1*-4*2+5 #Multiplying matrix mat1 with constant value 4
print(prod) #Printing the product

     [,1] [,2] [,3] [,4]
[1,]   -3  -35   -3  -35
[2,]  -11  -43  -11  -43
[3,]  -19  -51  -19  -51
[4,]  -27  -59  -27  -59


In [34]:
prod <- mat1*mat2 #Multiplying matrix mat1 with mat2
print(prod) #Printing the product

     [,1] [,2] [,3] [,4]
[1,]    1   25    9   65
[2,]    4   36   20   84
[3,]    9   49   33  105
[4,]   16   64   48  128


In [35]:
div <- mat1/mat2 #Division of mat1 and mat2 
print(div) #Printing the division

     [,1] [,2]      [,3]      [,4]
[1,]    1    1 0.1111111 0.3846154
[2,]    1    1 0.2000000 0.4285714
[3,]    1    1 0.2727273 0.4666667
[4,]    1    1 0.3333333 0.5000000


In [58]:
m=matrix(1:12,3,4)
print("Original matrix:")
print(m)
a = as.vector(m)
print("1 dimensional array:")
print(a)

[1] "Original matrix:"
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12
[1] "1 dimensional array:"
 [1]  1  2  3  4  5  6  7  8  9 10 11 12
