A vector is what is called an array in all other programming languages except R — a collection of cells with a fixed size where all cells hold the same type (integers or characters or reals or whatever).

A list can hold items of different types and the list size can be increased on the fly. List contents can be accessed either by index (like mylist[[1]]) or by name (like mylist$age).

A matrix is a two-dimensional vector (fixed size, all cell types the same).

An array is a vector with one or more dimensions. So, an array with one dimension is (almost) the same as a vector. An array with two dimensions is (almost) the same as a matrix. An array with three or more dimensions is an n-dimensional array.


("a","b",(1,(5,2)),5,6)

# R Vectors
A vector is simply a list of items that are of the same type.

To combine the list of items to a vector, use the c() function and separate the items by a comma.


In [43]:
# Vector of strings
fruits <- c("banana", "apple", "orange")

# Print fruits
fruits

[1] "banana" "apple"  "orange"

In [44]:
# Vector of numerical values
numbers <- c(1, 2, 3)

# Print numbers
numbers

[1] 1 2 3

In [45]:
# Vector with numerical values in a sequence
numbers <- 1:10

numbers

[1]  1  2  3  4  5  6  7  8  9 10

In [46]:
# Vector with numerical decimals in a sequence
numbers1 <- 1.5:6.5
numbers1

# Vector with numerical decimals in a sequence where the last element is not used
numbers2 <- 1.5:6.3
numbers2

[1] 1.5 2.5 3.5 4.5 5.5 6.5

[1] 1.5 2.5 3.5 4.5 5.5

In [47]:
# Vector of logical values
log_values <- c(TRUE, FALSE, TRUE, FALSE)

log_values

[1]  TRUE FALSE  TRUE FALSE

In [50]:
fruits <- c("banana", "apple", "orange")

a=length(fruits)
a

[1] 3

In [49]:
fruits <- c("banana", "apple", "orange", "mango", "lemon")
numbers <- c(13, 3, 5, 7, 20, 2)

sort(fruits)  # Sort a string
sort(numbers) # Sort numbers

[1] "apple"  "banana" "lemon"  "mango"  "orange"

[1]  2  3  5  7 13 20

In [51]:
fruits <- c("banana", "apple", "orange")

# Access the first item (banana)
fruits[1]

[1] "banana"

In [55]:
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Access the first and third item (banana and orange)
fruits[c(1:5)]  

[1] "banana" "apple"  "orange" "mango"  "lemon"

In [56]:
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Access all items except for the first item
fruits[c(-1)]

[1] "apple"  "orange" "mango"  "lemon"

In [57]:
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Change "banana" to "pear"
fruits[1] <- "pear"

# Print fruits
fruits

[1] "pear"   "apple"  "orange" "mango"  "lemon"

In [13]:
repeat_each <- rep(c(1,2,3), each = 3)

repeat_each

[1] 1 1 1 2 2 2 3 3 3

In [14]:
repeat_times <- rep(c(1,2,3), times = 3)

repeat_times

[1] 1 2 3 1 2 3 1 2 3

In [15]:
repeat_indepent <- rep(c(1,2,3), times = c(5,2,1))

repeat_indepent

[1] 1 1 1 1 1 2 2 3

In [16]:
numbers <- 1:10

numbers

[1]  1  2  3  4  5  6  7  8  9 10

In [60]:
numbers <- seq(from = 5.0, to = 100.0)

numbers

[1]   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23
[20]  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42
[39]  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61
[58]  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80
[77]  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
[96] 100

A list in R can contain many different data types inside it. A list is a collection of data which is ordered and changeable.

To create a list, use the list() function:

In [61]:
# List of strings
thislist <- list("apple", "banana", "cherry")

# Print the list
thislist

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

In [ ]:
thislist <- list("apple", "banana", "cherry")

thislist[1]

In [62]:
thislist <- list("apple", "banana", "cherry")
thislist[1] <- "blackcurrant"

# Print the updated list
thislist

[[1]]
[1] "blackcurrant"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

In [3]:
thislist <- list("apple", "banana", "cherry")

length(thislist)

[1] 3

In [66]:
thislist <- list("apple", "banana", "cherry")

"Apple" %in% thislist

[1] FALSE

In [ ]:
thislist <- list("apple", "banana", "cherry")

append(thislist, "orange")

In [70]:
thislist <- list("apple", "banana", "cherry")
a=append(thislist, "orange", after = 2)
thislist
a

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "orange"

[[4]]
[1] "cherry"

In [40]:
thislist <- list("apple", "banana", "cherry")

newlist <- thislist[-1]

# Print the new list
newlist

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

In [41]:
thislist <- list("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")

(thislist)[2:5]

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

[[3]]
[1] "orange"

[[4]]
[1] "kiwi"

In [ ]:
thislist <- list("apple", "banana", "cherry")

for (x in thislist) {
  print(x)
}

In [42]:
list1 <- list("a", "b", "c")
list2 <- list(1,2,3)
list3 <- c(list1,list2)

list3

[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"

[[4]]
[1] 1

[[5]]
[1] 2

[[6]]
[1] 3

# R Arrays

In [7]:
# An array with one dimension with values ranging from 1 to 24
thisarray <- c(1:24)
thisarray

# An array with more than one dimension
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray
#The first and second number in the bracket specifies the amount of rows and columns.
#The last number in the bracket specifies how many dimensions we want.

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

In [6]:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

multiarray[2, 3, 2]

[1] 22

In [5]:
thisarray <- c(1:24)

# Access all the items from the first row from matrix one
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[c(1),,1]

# Access all the items from the first column from matrix one
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[,c(1),1]

[1] 1 5 9

[1] 1 2 3 4

In [8]:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

2 %in% multiarray

[1] TRUE

In [ ]:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

dim(multiarray)

In [9]:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

length(multiarray)

[1] 24

In [10]:
multiarray <- array(thisarray, dim = c(4, 3, 2))

for(x in multiarray){
  print(x)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24


In [71]:
# Create a matrix
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2)

# Print the matrix
thismatrix

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [11]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

In [72]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[1, 2]

[1] "cherry"

In [73]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[2,]

[1] "banana" "orange"

In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[,2]

In [75]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)
thismatrix
thismatrix[c(1,2),]

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

[,1]   [,2]   [,3] 
[1,] apple  orange pear 
[2,] banana grape  melon

In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[, c(1,2)]

In [ ]:
#Use the cbind() function to add additional columns in a Matrix
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- cbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- rbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)

#Remove the first row and the first column
thismatrix <- thismatrix[-c(1), -c(1)]

thismatrix

In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

"apple" %in% thismatrix

In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

dim(thismatrix)

In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

length(thismatrix)

In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

for (rows in 1:nrow(thismatrix)) {
  for (columns in 1:ncol(thismatrix)) {
    print(thismatrix[rows, columns])
  }
}

In [ ]:
# Combine matrices
Matrix1 <- matrix(c("apple", "banana", "cherry", "grape"), nrow = 2, ncol = 2)
Matrix2 <- matrix(c("orange", "mango", "pineapple", "watermelon"), nrow = 2, ncol = 2)

# Adding it as a rows
Matrix_Combined <- rbind(Matrix1, Matrix2)
Matrix_Combined

# Adding it as a columns
Matrix_Combined <- cbind(Matrix1, Matrix2)
Matrix_Combined